#!/usr/bin/env python3
"""Aggregate the full-LoCoMo sweep into outputs/.../REPORT.md."""

from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SWEEP = REPO / "outputs" / "sweeps/2026-05-08_full_locomo"
OUT = SWEEP / "REPORT.md"

ROW_ORDER = [
    ("v1_best",          "hi-em-full-v1 (α=1, λ=10, σ²₀=0.01)"),
    ("v3p1p1_best",      "hi-em-full-v3.1.1 (α=10, λ=10, cos=0.3)"),
    ("v3p3p1_best",      "hi-em-full-v3.3.1 (cos=0.9, α=100, β=0.25)"),
    ("v3p3p2_best",      "hi-em-full-v3.3.2 (+ pe=0.5, train_steps=3)"),
    ("rag",              "rag"),
    ("rag_summary",      "rag-summary"),
    ("rag_observation",  "rag-observation"),
    ("sliding",          "sliding"),
    ("full",             "full (entire history → LLM)"),
]


def _parse_iso(s: str) -> datetime | None:
    try:
        return datetime.fromisoformat(s.strip())
    except Exception:
        return None


def wall_seconds(log_path: Path) -> float | None:
    if not log_path.exists():
        return None
    starts, ends = [], []
    for line in log_path.open():
        m = re.match(r"=== START (\S+) ===", line)
        if m:
            t = _parse_iso(m.group(1))
            if t: starts.append(t)
            continue
        m = re.match(r"=== END (\S+) ===", line)
        if m:
            t = _parse_iso(m.group(1))
            if t: ends.append(t)
    if starts and ends:
        return (ends[-1] - starts[0]).total_seconds()
    return None


def load_summary(run_dir: Path) -> dict:
    sp = list((run_dir / "results" / "experiments").glob("*/summary.json"))
    return json.loads(sp[0].read_text()) if sp else {}


def load_topk(run_dir: Path) -> dict:
    tk = run_dir / "stm_topk.json"
    return json.loads(tk.read_text()) if tk.exists() else {}


def n_topics_avg(run_dir: Path) -> float:
    rj = run_dir / "stm_topk.rounds.jsonl"
    if not rj.exists():
        return 0.0
    n = []
    for line in rj.open():
        if line.strip():
            try:
                n.append(json.loads(line).get("n_stm_topics", 0))
            except Exception:
                pass
    return sum(n) / len(n) if n else 0.0


def f(v, dp=3):
    if v is None or v == "":
        return "-"
    try:
        return f"{float(v):.{dp}f}"
    except Exception:
        return str(v)


def row(label: str, name: str) -> str:
    d = SWEEP / label
    if not d.exists() or not (d / "exit_code.txt").exists():
        return f"| {name} | - | - | - | - | - | - | - | - | - | - | - | - | - | - |"
    s = load_summary(d)
    tk = load_topk(d)
    t1 = tk.get("top1_per_round", {})
    t2 = tk.get("top2_per_round", {})
    t3 = tk.get("top3_per_round", {})
    acc = s.get("accuracy_overall", "-")
    mh = s.get("accuracy_by_qtype/multi-hop", "-")
    sh = s.get("accuracy_by_qtype/single-hop", "-")
    tr = s.get("accuracy_by_qtype/temporal-reasoning", "-")
    adv = s.get("accuracy_by_qtype/adversarial", "-")
    od = s.get("accuracy_by_qtype/open-domain", "-")
    gen_p50 = s.get("gen_sec_p50", "-")
    wall = wall_seconds(d / "run.log")
    n_q = s.get("n_questions", "-")
    return (
        f"| {name} | {n_q} | {f(acc)} | {f(mh)} | {f(sh)} | {f(tr)} | {f(adv)} | {f(od)} | "
        f"{f(t1.get('mean'),1)} | {f(t2.get('mean'),1)} | {f(t3.get('mean'),1)} | "
        f"{t1.get('max','-')} | {t2.get('max','-')} | {f(t1.get('variance'),1)} | "
        f"{f(n_topics_avg(d),2)} | {f(gen_p50,2)} | {f(wall,1)} |"
    )


def main() -> None:
    SWEEP.mkdir(parents=True, exist_ok=True)
    header = (
        "| method | n | acc | multi-hop | single-hop | temporal | adversarial | open-dom | "
        "T1μ | T2μ | T3μ | T1max | T2max | T1var | n_topics_avg | gen_p50(s) | wall(s) |"
    )
    sep = "|" + "---|" * 17

    lines: list[str] = []
    lines.append("# Full LoCoMo sweep — best Hi-EM configs vs all baselines\n")
    lines.append("Generated by `scripts/aggregate_full_locomo.py`. Date: 2026-05-08.\n")
    lines.append("Full LoCoMo (10 conv / 1986 Q, no --limit, no --stratify). "
                 "Each Hi-EM run uses the best HPs from prior sweeps. "
                 "v3.2.1 intentionally skipped per user request.\n")
    lines.append("- T1μ/T2μ/T3μ: mean STM top-1/2/3 topic turn-counts across rounds.")
    lines.append("- T1var: variance of top-1 across rounds. n_topics_avg: mean STM topic count per round.")
    lines.append("- gen_p50(s): per-question generation time p50. wall(s): full run wall-clock.\n")
    lines.append(header)
    lines.append(sep)
    for label, name in ROW_ORDER:
        lines.append(row(label, name))
    lines.append("")

    # Best summary
    lines.append("## 자동 추출: best (acc 기준)\n")
    best: tuple[str, float] | None = None
    for label, name in ROW_ORDER:
        d = SWEEP / label
        if not (d / "exit_code.txt").exists():
            continue
        s = load_summary(d)
        acc = s.get("accuracy_overall")
        if acc is None: continue
        if best is None or float(acc) > best[1]:
            best = (name, float(acc))
    if best:
        lines.append(f"- **best**: `{best[0]}` — acc = {best[1]:.3f}")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"report → {OUT}")


if __name__ == "__main__":
    main()
